name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
